// KCGM plant knowledge question bank.
// Each question: t = topic key, q = question, a = answers (FIRST is correct, shuffled at runtime), e = explanation.
// Sources: Plant Numbering Spec 2000-F00-STS-GE-10003, Growth Project WBS, Stage 2 Process Design
// Criteria 2000-F00-DCR-PR-10002 Rev 4, Stage 1 as-built PFDs, Overall Plant Layout 2000-F00-DRG-GE-20001.

const TOPICS = {
  big:   { name: "Big Picture", icon: "🧭", blurb: "Why the flowsheet looks the way it does" },
  codes: { name: "Area Codes", icon: "🔢", blurb: "F12, F16, F21... what people mean" },
  tags:  { name: "Reading Tags", icon: "🏷️", blurb: "Equipment, motor, cable and instrument tags" },
  acro:  { name: "Acronyms & Slang", icon: "💬", blurb: "The words you hear on the radio" },
  crush: { name: "Crushing", icon: "🪨", blurb: "ROM pad to coarse ore stockpile" },
  mill:  { name: "Milling & Classification", icon: "⚙️", blurb: "SAG, ball mill, pebbles, cyclones" },
  grav:  { name: "Gravity & ILR", icon: "✨", blurb: "Knelsons, intensive leach, gravity EW" },
  flot:  { name: "Flotation", icon: "🫧", blurb: "Roughers, scavengers, Jamesons" },
  conc:  { name: "Concentrate & UFG", icon: "🔬", blurb: "Thickening, IsaMills, CIL2/3" },
  cil4:  { name: "Tails Leach (CIL4)", icon: "🛢️", blurb: "Flotation tails thickener and CIL4" },
  elu:   { name: "Elution, Regen & Goldroom", icon: "🔥", blurb: "Stripping carbon and pouring doré" },
  util:  { name: "Water, Air & Reagents", icon: "💧", blurb: "Services that keep it all running" },
  nums:  { name: "Key Numbers", icon: "📊", blurb: "Throughput, grades, recoveries" },
  hand:  { name: "Shift Handover Scenarios", icon: "📻", blurb: "What does that report actually mean?" }
};

const QUESTIONS = [
// ───────────────────────── BIG PICTURE ─────────────────────────
{t:"big",q:"Why can't KCGM simply grind the ore and put it all straight into cyanide leach?",
 a:["Much of the gold is locked inside sulphide minerals (mainly pyrite), so cyanide can't reach it","The ore is too soft to grind finely","Cyanide is banned at Fimiston","The gold is too coarse and settles out in the tanks"],
 e:"KCGM ore is refractory. A large share of the gold is locked inside pyrite and tellurides. Think of it like a bolt seized inside a housing: the solvent (cyanide) can't get to it until you break the housing. That is why the flowsheet splits ore into a sulphide concentrate for extra treatment."},
{t:"big",q:"In one sentence, what are the two gold 'paths' through the plant?",
 a:["Free gold is leached from the bulk tails (CIL4), while sulphide concentrate is floated off, ultra fine ground and leached hard (CIL2/3)","Oxide ore goes to heap leach, sulphide ore goes to the roaster","Coarse ore goes to gravity, fine ore goes to tailings","Day shift ore goes to CIL2, night shift ore goes to CIL4"],
 e:"Almost every conversation maps to one of these two streams. The big, low grade stream (about 96% of the mass) is flotation tails leached in CIL4. The small, rich stream (about 4% of the mass) is the sulphide concentrate that gets UFG treatment then an aggressive leach in CIL2/3. Gravity skims off coarse free gold early."},
{t:"big",q:"What does flotation actually separate at KCGM?",
 a:["Sulphide minerals (pyrite carrying locked gold) from the non sulphide gangue","Gold nuggets from water","Carbon from slurry","Tellurium from copper"],
 e:"Flotation makes sulphide particles water repellent so they stick to air bubbles and rise into the froth. The design sulphur recovery to concentrate is about 85%. Gold follows the sulphur because it is locked inside it."},
{t:"big",q:"Why grind the concentrate down to about 9 µm in the UFG mills?",
 a:["To physically break open the pyrite and expose locked gold to cyanide","To make the concentrate easier to truck","To reduce cyanide consumption to zero","To make the slurry float better"],
 e:"UFG (IsaMills) replaces the old roasting route. Instead of burning the sulphide off, you grind so fine that the gold bearing pyrite grains are cracked open. It costs a lot of energy per tonne (around 116 kWh/t) but only on the small concentrate mass."},
{t:"big",q:"Historically, where was the KCGM concentrate treated before the Growth Project consolidated it at Fimiston?",
 a:["Gidji, first through a roaster and later through ultra fine grinding","Mt Charlotte underground","Kalgoorlie Consolidated's Perth refinery","It was shipped overseas only"],
 e:"Concentrate used to be hauled to Gidji. Stage 2 consolidates processing into a single hub at Fimiston, removing the concentrate haulage and targeting a 1 to 2% recovery uplift."},
{t:"big",q:"What does gravity recovery (Knelsons + ILR) catch that flotation and CIL would struggle with?",
 a:["Coarse free gold that is heavy, recirculates in the mill circuit and leaches slowly","Fine gold locked in pyrite","Sulphur","Carbon fines"],
 e:"Coarse gold is so dense it tends to sit in the cyclone underflow and cycle through the ball mill again and again. Gravity pulls it out early. Design gravity recovery is about 14% of feed gold nominal, up to 20%."},
{t:"big",q:"Put these in the correct order for the bulk ore stream: (1) Flotation (2) SAG mill (3) Primary crusher (4) Cyclones (5) CIL4",
 a:["3 → 2 → 4 → 1 → 5","2 → 3 → 1 → 4 → 5","3 → 4 → 2 → 5 → 1","3 → 2 → 1 → 4 → 5"],
 e:"Crush, SAG mill, classify in cyclones (ball mill closes the loop), cyclone overflow through trash screens to rougher/scavenger flotation, then flotation tails are thickened and leached in CIL4."},
{t:"big",q:"Why does the plant use activated carbon in the leach tanks (CIL = Carbon in Leach)?",
 a:["Carbon adsorbs the dissolved gold cyanide from solution so it can be screened out and stripped later","Carbon neutralises the cyanide","Carbon grinds the ore finer","Carbon floats the sulphides"],
 e:"Leaching dissolves gold into solution. Carbon granules act like a sponge for gold cyanide. Because the carbon is much coarser than the slurry, it can be held back by intertank screens and moved counter current, then pulled out loaded and sent to elution."},
{t:"big",q:"What is 'Stage 1' vs 'Stage 2' of the Growth Project in simple terms?",
 a:["Stage 1 builds the new crushing, milling, gravity, flotation and CIL4 capacity; Stage 2 brings concentrate treatment (UFG, CIL2/3) into a single Fimiston hub","Stage 1 is mining, Stage 2 is processing","Stage 1 is day shift, Stage 2 is night shift","Stage 1 is oxide ore, Stage 2 is sulphide ore"],
 e:"The drawings carry legends like 'SP1 AS BUILT' and 'SP2 NEW / SP2 DECOMMISSIONED'. SP means Separable Portion, the contract packages for Stage 1 and Stage 2."},
{t:"big",q:"On a PFD legend you see 'SP2 DECOMMISSIONED'. What does that line mean?",
 a:["That equipment or line is removed from service as part of Stage 2 (Separable Portion 2)","It is a spare pump","It was never built","It carries sulphuric acid"],
 e:"SP = Separable Portion. Old plant items retired in the Stage 2 changeover are shown in that colour. Handy when people say 'that's gone in SP2'."},

// ───────────────────────── AREA CODES ─────────────────────────
{t:"codes",q:"What is Area F12?",
 a:["Primary Crushing (new)","Milling & Classification","Rougher & Scavenger Flotation","Final Tailings"],
 e:"F10 is the existing Fimiston primary crusher (Primary Crushing 1). F12 is the new primary crushing area (Primary Crushing 2), including the crushed ore stockpile and conveyors."},
{t:"codes",q:"What is Area F10?",
 a:["Primary Crushing, Fimiston Existing","Pebble Crushing","Reagents","Ultra Fine Grinding 2/3"],
 e:"F10 = the existing Fimiston primary crusher. On the PFDs it is 'Primary Crushing 1' feeding the coarse ore stockpile."},
{t:"codes",q:"What is Area F13?",
 a:["Milling & Classification (new SAG, ball mill, pebble crushing, cyclones, trash screens)","Gravity Circuit","Concentrate Filtration","Air Services"],
 e:"F13 is where the new SAG mill (F13-MS-401) and ball mill (F13-MB-401) live, plus stockpile reclaim, pebble crushing, cyclones and trash screens."},
{t:"codes",q:"What is Area F14?",
 a:["Gravity Circuit & Intensive Leaching","Flotation Tailings Pre-Leach Thickening","Electrowinning & Goldroom","Mt Charlotte Stockpile"],
 e:"F14 covers the gravity cyclones, scalping screens, Knelson concentrators and the Acacia intensive leach reactor (ILR)."},
{t:"codes",q:"What is Area F15?",
 a:["Mt Charlotte Stockpile / Reclaim","Rougher Flotation","Cyanide Destruct","Carbon Regeneration"],
 e:"F15 = Mt Charlotte stockpile and reclaim. You'll see F15 tags on the coarse ore conveyor feeding the Fimiston SAG mill."},
{t:"codes",q:"What is Area F16?",
 a:["Rougher & Scavenger Flotation","Cleaner Flotation","Flotation Tails CIL4","Water Services"],
 e:"F16 = the big forced air tank cells: 3 rougher cells (F16-CF-411 to 413) then 4 scavenger cells (F16-CF-414 to 417)."},
{t:"codes",q:"What is Area F17?",
 a:["Flotation Tailings Pre-Leach Thickening","Cleaner Scavenger Flotation","Final Tails Pumping","Gravity Electrowinning"],
 e:"F17 thickens the scavenger tails and cleaner-scavenger tails before they go to CIL4. Thickening raises the slurry density so the leach tanks give more residence time for the same volume."},
{t:"codes",q:"What is Area F18?",
 a:["Cleaner & Cleaner-Scavenger Flotation (the Jameson cells)","Rougher Flotation","Concentrate Handling","Reagent Storage"],
 e:"F18 holds the two Glencore Jameson B6500/24 cells, one on cleaner duty and one on cleaner-scavenger duty, plus the final concentrate hopper (F18-HP-414)."},
{t:"codes",q:"What is Area F19?",
 a:["Milling & Classification, Fimiston Existing (Area A)","Flotation Tails CIL4","Final Tailings","Oxygen Plant"],
 e:"F19 is the old Fimiston SAG mill area (F19-MS-61). Its discharge is now pumped across to the new primary cyclone feed hopper so both SAGs share the new ball mill and cyclone cluster."},
{t:"codes",q:"What is Area F21?",
 a:["Flotation Tailings CIL4","CIL4 Elution","Concentrate CIL2/3","Air & Water Services"],
 e:"F21 = CIL4, the new leach and adsorption tanks for the flotation tails (F21-TK-411 to 418)."},
{t:"codes",q:"What is Area F22?",
 a:["CIL4 Carbon Treatment & Elution (incl. CIL4 carbon regeneration)","Final Tails","Rougher Flotation","Primary Crushing"],
 e:"F22 is the carbon side of CIL4: loaded carbon screen, acid wash/elution column, carbon regeneration kiln and the kiln off gas treatment."},
{t:"codes",q:"What is Area F23?",
 a:["Final Tailings Handling & Storage","Reagents","Gravity","UFG Existing"],
 e:"F23 covers the final tails tank, final tails pumps and booster pumps sending tailings to the storage facility (Fim III TSF is WBS T03)."},
{t:"codes",q:"What is Area F24?",
 a:["Air & Water Services (process, gland, raw, saline water, plant and instrument air)","Cleaner Flotation Existing","Concentrate Filtration","Electrowinning"],
 e:"F24 is the new services area. Existing services have their own codes: F75 Water Services Existing and F81 Air Services Existing."},
{t:"codes",q:"What is Area F28?",
 a:["Ultra Fine Grinding 2/3 (the new IsaMills)","Ultra Fine Grinding Existing","Pebble Crushing","Trash Screening"],
 e:"F28 = the two new M15,000 IsaMills. The existing UFG (UFG 1, an M3000) is F34."},
{t:"codes",q:"What is Area F30?",
 a:["Concentrate Pre-Leach Thickening, CIL2/3 & Post-Leach Thickening","Flotation Tails CIL4","Crushing","Goldroom"],
 e:"F30 is the concentrate leach side. CIL2 is repurposed for leach duty, CIL3 for adsorption. You'll see tags like 30-TK-32A and F30-TK-62A."},
{t:"codes",q:"What is Area F34?",
 a:["Ultra Fine Grinding, Existing (UFG 1)","Concentrate Carbon Treatment","Reagents","Final Tails"],
 e:"F34 = the existing UFG 1 IsaMill (M3000). New UFG 2 and 3 are F28."},
{t:"codes",q:"What is Area F35?",
 a:["Concentrate Handling & Filtration","Cleaner Scavenger Flotation Existing","Water Services Existing","Primary Crushing"],
 e:"F35 covers the concentrate thickener, filter feed tanks, vacuum belt filters and concentrate stockpile. Filters stay in service to handle concentrate in excess of UFG capacity."},
{t:"codes",q:"What is Area F65?",
 a:["Concentrate Carbon Treatment & Elution (the CIL2/3 carbon side)","CIL4 Elution","Reagent Mixing","Cyanide Destruct"],
 e:"F65 handles loaded carbon from CIL3: carbon transfer vessels, acid wash, elution and quench tanks. CIL4's equivalent is F22."},
{t:"codes",q:"What is Area F66?",
 a:["Electrowinning & Goldroom","Oxygen Plant","Lime Plant","Tailings"],
 e:"F66 covers CIL4A/4B electrowinning, gravity electrowinning and the goldroom where cathode product is smelted to doré."},
{t:"codes",q:"What is Area F72?",
 a:["Reagents Mixing & Storage","Flotation","Crushing","Water Services Existing"],
 e:"F72 WBS lines: PAX, frother, copper sulphate, oxygen, caustic, acid, cyanide, lead nitrate, LNG, lime and flocculant. F70 is the existing lime plant and flocculant, F71 existing reagents."},
{t:"codes",q:"What is Area F78?",
 a:["Carbon Regeneration, Existing","Air Services Existing","Water Services Existing","Gravity"],
 e:"F78 = the existing carbon regeneration kiln area. F75 = existing water services, F81 = existing air services."},
{t:"codes",q:"Someone says 'it's in 25/26'. Which areas are those?",
 a:["Existing Cleaner Flotation (F25) and existing Cleaner Scavenger Flotation (F26)","CIL4 trains A and B","UFG 2 and 3","Crushing 1 and 2"],
 e:"F25 and F26 are the old cleaner circuits. The new cleaning circuit is F18 (Jameson cells)."},
{t:"codes",q:"What does the leading 'F' in every Growth Project tag stand for?",
 a:["Fimiston Site","Flotation","Feed","Facility number"],
 e:"All Growth Project equipment carries the F prefix for Fimiston. In the WBS, level 1 letters are M Mining, F Fimiston Processing, T Tailings, N Non-Process Infrastructure, P Indirects."},
{t:"codes",q:"In the WBS, what is T03?",
 a:["Fim III Tailings Storage Facility (TSF)","Tailings Pump 3","Train 3 of CIL4","Thickener 3"],
 e:"T = Tailings Facility. T03 covers the Fim III TSF, tailings pipeline, distribution, and return water."},
{t:"codes",q:"In the WBS, what is N02?",
 a:["Kaltails Borefields (saline water supply)","Northern Crusher 2","New Pebble Crusher","Nitrogen plant"],
 e:"N = Non-Process Infrastructure. N02 Kaltails Borefields includes pump stations, pipelines and the RO / acid water treatment. It is one of the saline water sources."},
{t:"codes",q:"A conveyor runs from F12 into F13. Which area code does it take?",
 a:["The area it feeds (head pulley location), so F13","The area it starts in, so F12","F00 because it crosses areas","F24 because it's a service"],
 e:"Per the Plant Numbering Spec, a conveyor takes the area code of the area it is feeding / where its head pulley sits."},
{t:"codes",q:"What is Area F00?",
 a:["General Fimiston Site (HV power, buried services, pipe racks, LV distribution)","The control room","The first crusher","Future area"],
 e:"F00 is site wide general scope. Documents like 2000-F00-PFD... are general project documents too."},

// ───────────────────────── TAGS ─────────────────────────
{t:"tags",q:"Decode F13-MS-401.",
 a:["Fimiston, Milling & Classification area, SAG Mill, number 401","Fimiston, Area 13, Main Switchboard 401","Flotation cell 13, Motor Starter 401","Feeder 13, Mill Screen 401"],
 e:"Format is Prefix-Area-EquipmentCode-Number. MS = SAG mill. New equipment numbers start at 401 so they never clash with existing plant numbers."},
{t:"tags",q:"Why do new Growth Project equipment numbers start at 401?",
 a:["To avoid duplicating existing plant equipment numbers","Because 400 items were cancelled","Because 4 = Stage 4","It is the year the design started"],
 e:"The spec says new equipment and new instruments in existing areas start at 401. So '4xx' is a quick hint you're looking at Growth Project kit, while low numbers like F19-MS-61 are legacy plant."},
{t:"tags",q:"Equipment code 'CF'?",
 a:["Flotation cell (column or cell)","Cone crusher","Conveyor feeder","Centrifugal fan"],
 e:"F16-CF-411 is Rougher Cell 1. F18-CF-501 is the cleaner Jameson cell."},
{t:"tags",q:"Equipment code 'MB'?",
 a:["Ball Mill","Motor Brake","Mill Bin","Magnetic Belt"],
 e:"F13-MB-401 = the new ball mill. MS = SAG mill, MU = existing UFG mill, MUF = new UFG mill."},
{t:"tags",q:"Equipment code 'CG'?",
 a:["Gyratory Crusher","Cone crusher","Carbon Gate","Cyclone Group"],
 e:"CG = gyratory crusher, CC = cone crusher (e.g. pebble crushers), CJ = jaw crusher."},
{t:"tags",q:"Equipment code 'CY'?",
 a:["Cyclone","Cylinder","Clarifier","Crane"],
 e:"F13-CY-401 = the primary cyclone cluster. CR = cranes and hoists."},
{t:"tags",q:"What's the difference between 'PP' and 'PS' pump codes?",
 a:["PP = process pump, PS = sump pump","PP = positive displacement, PS = slurry","PP = pump primary, PS = pump secondary","PP = peroxide pump, PS = sulphate pump"],
 e:"PP for process duty pumps (e.g. cyclone feed pump F13-PP-401), PS for area sump pumps. PW = water pump, PT = transfer pump, PV = vacuum pump."},
{t:"tags",q:"Code 'SU' vs 'PS'. Which is the sump itself?",
 a:["SU is the sump only; PS is the sump pump","PS is the sump only; SU is the pump","Both mean sump pump","SU means surge tank"],
 e:"The spec explicitly says SU = 'Sump (Sump Only! Not Sump Pump)'."},
{t:"tags",q:"Code 'FA'?",
 a:["Apron Feeder","Fan","Flotation Aerator","Filter Assembly"],
 e:"Feeders: FA apron, FB belt, FV vibrating, FS screw. Apron feeders sit under the crusher discharge and the stockpile."},
{t:"tags",q:"Code 'TH'?",
 a:["Thickener","Tank Heater","Trash Hopper","Transfer Hose"],
 e:"TH = thickener, TK = tank, AG = agitator, RK = rake mechanism."},
{t:"tags",q:"Code 'IL'?",
 a:["Intensive Leach Reactor","Inline mixer","Instrument Loop","Intertank Launder"],
 e:"The ILR (Acacia CS10000) leaches the Knelson gravity concentrate in batches."},
{t:"tags",q:"Code 'CN'?",
 a:["Elution Column","Cone","Conveyor","Condenser"],
 e:"CN = elution column. KN = kiln (carbon regeneration). CL/EC = electrowinning cells (new/existing). ER = electrowinning rectifier."},
{t:"tags",q:"Code 'WD'?",
 a:["Weightometer (belt scale)","Water Dam","Wet Drive","Wood Dewatering"],
 e:"Weightometers measure tonnes per hour on conveyors, e.g. the SAG mill feed conveyor weightometer. They're your main throughput signal."},
{t:"tags",q:"Code 'MG'?",
 a:["Electro Magnet (tramp metal magnet)","Motor Generator","Mill Gear","Media Grinding"],
 e:"Tramp magnets on conveyors pull out steel (rock bolts, mesh, ground engaging tools) that would damage crushers and belts."},
{t:"tags",q:"The motor on pump F21-PU-001 is tagged how?",
 a:["F21PU001 (same number, dashes removed)","F21-MO-001","M-F21-001","F21PU001-M"],
 e:"Motors take the parent equipment number with dashes removed. Its VSD would be F21PU001-VS, its local control station F21PU001-LCS."},
{t:"tags",q:"Cable F21PU001-P1 vs F21PU001-C2. What's the difference?",
 a:["P1 is power cable number 1; C2 is control cable number 2 to the same equipment","P1 is pump 1; C2 is cyclone 2","P1 is phase 1; C2 is circuit 2","P1 is primary; C2 is contingency"],
 e:"Circuit types: P power, N neutral, I instrumentation, C control, E earth, D digital/Ethernet, DC direct current, F fire, FO fibre optic."},
{t:"tags",q:"Decode instrument tag FIT13001.",
 a:["Flow Indicating Transmitter, Area 13, loop 001","Feeder Inlet Temperature, Tank 13","Fan Isolation Trip 13","Filter Inlet Transducer 13001"],
 e:"Instrument tags = letters + area + loop number. First letter is the measured variable (F flow), following letters the function (I indicate, T transmit). All parts of one loop share the number, e.g. PT13001, PIC13001, PCV13001."},
{t:"tags",q:"What does the first letter 'D' in an instrument tag like DT or DIT usually measure?",
 a:["Density","Differential","Dust","Discharge"],
 e:"First letter D = density (slurry density gauges, often nuclear). As a second letter D means differential. Density is critical on cyclone feed, thickener underflow and leach feed."},
{t:"tags",q:"First letter 'L' in an instrument tag?",
 a:["Level","Load","Lime","Line"],
 e:"LT = level transmitter, LIC = level indicating controller. Sump, hopper and tank levels drive most pump speed loops."},
{t:"tags",q:"First letter 'A' (e.g. AE, AIT)?",
 a:["Analysis (pH, DO, cyanide, particle size etc.)","Air","Alarm","Agitator"],
 e:"A = analysis. As a second letter A means alarm, e.g. LAH = level alarm high."},
{t:"tags",q:"What does 'LAH' mean on a P&ID?",
 a:["Level Alarm High","Lime Addition Header","Low Amp Hold","Line A Heater"],
 e:"First letter L level, second letter A alarm, third letter H high. LAL would be level alarm low. Same pattern for PAH, TAH etc."},
{t:"tags",q:"Electrical code 'SW' on the Growth Project?",
 a:["Switchboard (HV and LV switchboards and MCCs)","Scheme Water","Screen Wash","Sample Weigher"],
 e:"The spec says MCCs are referred to as switchboards, code SW. SR is the switchroom building, TR transformer, VS variable speed drive, SS soft starter."},
{t:"tags",q:"Electrical code 'LCS'?",
 a:["Local Control Station (field start/stop panel)","Lime Control System","Level Control Switch","Loaded Carbon Screen"],
 e:"The LCS is the push button station next to a drive, used for local operation and isolations. Tagged like F21PU001-LCS."},
{t:"tags",q:"Code 'VL'?",
 a:["Launder / Sump / Kibble","Valve Line","Vent Louvre","Vacuum Line"],
 e:"On the flotation PFD, F16-VL-440 is the scavenger concentrate collection launder and F16-VL-438 the rougher 2 & 3 concentrate launder."},
{t:"tags",q:"Code 'SA' (as in F18-SA-403)?",
 a:["Isa Sampler (process sampler)","Safety Air","Screen Assembly","Sulphuric Acid"],
 e:"SA samplers cut samples for the onstream analyser and metallurgical accounting, e.g. the final concentrate sampler."},
{t:"tags",q:"Code 'RB' at the crusher?",
 a:["Rock Breaker","Rubber Belt","Rotary Bin","Reclaim Bunker"],
 e:"F10-RB-01 is the rock breaker on the crusher. It breaks oversize rocks that bridge in the crusher throat."},
{t:"tags",q:"Code 'CV'?",
 a:["Conveyor","Control Valve","Cyanide Vessel","Cyclone Vortex"],
 e:"Conveyors are CV (e.g. F19-CV-21 recycle conveyor). Control valves are instrument tags like FCV or LCV."},

// ───────────────────────── ACRONYMS ─────────────────────────
{t:"acro",q:"'ROM'?",a:["Run of Mine (ore as delivered from the pit)","Rate of Milling","Return Overflow Material","Recovery Optimisation Model"],
 e:"ROM ore arrives in CAT 793F haul trucks (about 250 t payload) and is tipped into the primary crusher dump pocket."},
{t:"acro",q:"'COS'?",a:["Coarse (Crushed) Ore Stockpile","Cyclone Overflow Solids","Carbon Out of Solution","Cyanide Oxidation Stage"],
 e:"The COS is the buffer between the crusher (65% availability) and the mills (93.4% availability). The new one holds roughly 20,000 t live, about 11 h of mill feed."},
{t:"acro",q:"'SABC'?",a:["SAG mill, Ball mill, pebble Crusher circuit","Standard Automatic Belt Conveyor","Sulphide And Base metal Concentrate","Stage A/B Commissioning"],
 e:"SABC: SAG mill does the coarse breakage, ball mill finishes the grind, pebble crushers break the critical size rocks the SAG can't handle."},
{t:"acro",q:"'SAG' mill?",a:["Semi Autogenous Grinding: the ore grinds itself with help from a small steel ball charge","Slurry And Grit mill","Secondary Attrition Grinder","Screen Assisted Grinding"],
 e:"The new SAG is 10.97 m diameter (36 ft) × 8.38 m EGL with a 20 MW motor, running about 10.5% balls and 27% total load by volume."},
{t:"acro",q:"'P80' of 180 µm means...",a:["80% of the product mass passes 180 µm","The top size is 180 µm","The average particle is 80 µm","80% of particles are above 180 µm"],
 e:"P80 = product size at 80% passing, F80 = feed size at 80% passing. The grind target to flotation is P80 180 µm (220 µm in the 28.35 Mtpa high throughput case)."},
{t:"acro",q:"'OSS' and 'CSS' on a crusher?",a:["Open Side Setting and Closed Side Setting (the max and min gap between mantle and concave)","Oversize Screen and Circulating Screen","On Stream Sampler and Cyclone Sampling System","Operating Safety System"],
 e:"The new gyratory runs about 165 mm OSS. The pebble cone crushers run about 7 mm CSS. Tighter setting = finer product but more power and wear."},
{t:"acro",q:"'CIL'?",a:["Carbon in Leach: leaching and carbon adsorption happen in the same tank train","Cyanide In Line","Crushed Ore In Leach","Concentrate Intermediate Leach"],
 e:"KCGM talks about CIL2/3 (concentrate) and CIL4 (flotation tails). In the Stage 2 concentrate circuit, CIL2 is used for leach duty and CIL3 for adsorption."},
{t:"acro",q:"'ILR'?",a:["Intensive Leach Reactor","Inline Lime Regulator","Intermediate Leach Residue","Instrument Loop Register"],
 e:"The ILR is an Acacia CS10000 batch reactor that leaches Knelson gravity concentrate with strong cyanide. About 98% leach recovery."},
{t:"acro",q:"'UFG'?",a:["Ultra Fine Grinding (IsaMills grinding concentrate to about 9 µm)","Upper Feed Gate","Underflow Gravity","Unit Final Grade"],
 e:"UFG 1 is the existing IsaMill M3000 (F34). UFG 2 and 3 are new M15,000 IsaMills (F28), about 3.5 MW draw each."},
{t:"acro",q:"'EW'?",a:["Electrowinning: plating gold out of pregnant solution onto cathodes","East Wing","Elution Water","Effluent Waste"],
 e:"Electrowinning passes current through cells so gold deposits on stainless steel cathodes. Cathode sludge then goes to the goldroom for smelting."},
{t:"acro",q:"'AARL' (as in split AARL elution)?",a:["Anglo American Research Laboratories elution method: hot caustic cyanide pre-soak then water elution","Automatic Acid Rinse Loop","Adsorption And Regeneration Line","Advanced Air Removal Loop"],
 e:"AARL: acid wash, pre-soak with caustic cyanide, then elute with hot water. 'Split' means part of the eluate is recycled as lean eluate for the next strip."},
{t:"acro",q:"'PAX'?",a:["Potassium Amyl Xanthate, the flotation collector","Plant Air Exchange","Primary Agitator X","Pregnant Aqueous eXtract"],
 e:"PAX coats sulphide surfaces making them water repellent so they attach to bubbles. It's dosed to rougher, scavenger and cleaner circuits."},
{t:"acro",q:"'CuSO₄' in flotation is used as...",a:["An activator, making pyrite surfaces more receptive to the collector","A frother","A pH modifier","A flocculant"],
 e:"Copper sulphate 'activates' pyrite. The PDC shows a dosing point at SAG mill discharge so it has conditioning time before flotation, plus cleaner dosing."},
{t:"acro",q:"'OSA'?",a:["Onstream Analyser (measures stream assays in near real time)","Oxygen Supply Air","Overflow Sample Automatic","Operating Standard Approval"],
 e:"Flotation feed, rougher concentrates, scavenger concentrate and tails, and final concentrate are all sampled to the OSA. It's how operators see grade and recovery trends shift by shift."},
{t:"acro",q:"'DO' in leach?",a:["Dissolved Oxygen","Discharge Overflow","Design Operating","Density Output"],
 e:"Cyanide leaching needs oxygen. Sulphide rich slurries consume oxygen, so CIL2 and CIL4 have oxygen side lances and oxygen injection pumps."},
{t:"acro",q:"'WAD cyanide'?",a:["Weak Acid Dissociable cyanide, the environmentally relevant cyanide measure","Water And Drainage cyanide","Waste After Detox","Weight Adjusted Dose"],
 e:"WAD CN is what regulators and wildlife care about at the TSF. Decant water is dosed with hydrogen peroxide to a residual WAD target, controlled by an online CNWAD analyser."},
{t:"acro",q:"'TSF'?",a:["Tailings Storage Facility","Thickener Solids Flux","Transfer Station F","Total Solids Feed"],
 e:"Final tails are pumped to the Fim III TSF (WBS T03). Decant water returns to the plant as cyanide water."},
{t:"acro",q:"'BV' in elution?",a:["Bed Volume (one volume of the carbon bed)","Ball Valve","Barren Vessel","Bulk Volume of ore"],
 e:"Elution steps are specified in BVs, e.g. 5 BVs of eluate. It scales the solution to the column size, like specifying flushing in 'system volumes'."},
{t:"acro",q:"'PSA' plant?",a:["Pressure Swing Adsorption oxygen plant","Plant Safety Assessment","Primary Screen Area","Pebble Size Analysis"],
 e:"The PSA plant makes oxygen for leaching (and the ILR) by adsorbing nitrogen from compressed air in cycling vessels. Liquid oxygen storage backs it up."},
{t:"acro",q:"'MoL'?",a:["Milk of Lime (slaked lime slurry for pH control)","Mill Operating Load","Measure of Loss","Main Overflow Line"],
 e:"Quicklime is slaked to milk of lime and distributed on a lime ringmain to the leach feed boxes. High pH stops toxic HCN gas forming."},
{t:"acro",q:"'TML' for concentrate?",a:["Transportable Moisture Limit (max moisture for safe bulk shipment)","Total Metal Loss","Tank Minimum Level","Thickener Mud Level"],
 e:"Concentrate filtered for the stockpile must be under its TML (about 6 to 8% w/w) or it can liquefy in transport. The filter target is below 10% moisture."},
{t:"acro",q:"'%Cs' when talking mill speed?",a:["Percent of critical speed (the speed at which the charge centrifuges)","Percent carbon solids","Percent copper sulphate","Percent cyclone split"],
 e:"The SAG runs 60 to 83% Cs on its VSD. Higher speed throws the charge harder (more impact) but risks liner damage if the load is low."},
{t:"acro",q:"'EGL' on a mill datasheet?",a:["Effective Grinding Length (inside liners)","Emergency Gear Lock","Estimated Gold Loss","External Guard Length"],
 e:"The new SAG EGL is 8.38 m vs 4.27 m on the old Fimiston SAG, same 10.97 m diameter. So nearly double the grinding volume."},
{t:"acro",q:"'Circ load' in the grinding circuit?",a:["Circulating load: cyclone underflow tonnes returned to the ball mill as a % of new feed","Circuit breaker load","Carbon in circuit","Cyanide circulating in leach"],
 e:"Design is around 358% cyclone underflow to overflow. A mechanical analogy is a recirculating pump loop: high circ load keeps the mill full of near sized material to grind efficiently."},
{t:"acro",q:"'Mass pull' in flotation?",a:["The % of feed mass that reports to concentrate","The torque on the rougher agitator","The pump suction pressure","The froth depth"],
 e:"Rougher 1 pulls about 4.4%, roughers 2&3 about 2.4%, scavengers about 1.1% of feed mass. Too high a pull dilutes grade and overloads the concentrate side."},
{t:"acro",q:"'Froth factor' in the PDC?",a:["A design multiplier on concentrate pump/pipe sizing because froth carries air and occupies more volume","Frother dosage","The number of froth crowders","Bubble size"],
 e:"Froth is a foam. The PDC applies factors of 1.6 to 2.5 to concentrate lines so pumps and launders don't airlock or overflow."},
{t:"acro",q:"'Scats'?",a:["Oversize rocks/steel rejected from the ball mill trommel","Scavenger tails","Sample cuts","Spare cathodes"],
 e:"The PFD shows a scats bunker by the ball mill trommel. Scats are worn balls and tough rocks that won't grind."},
{t:"acro",q:"'NSR' on drawings?",a:["Northern Star Resources (the owner)","Nominal Solids Rate","New Screen Room","Non Standard Request"],
 e:"NSR is the owner. Primero was the EPC contractor. PDC = Process Design Criteria, TQ = Technical Query, SysCAD = the mass balance modelling software."},
{t:"acro",q:"'TQ' in project documents?",a:["Technical Query, a formal question and answer between contractor and owner","Total Quantity","Thickener Quality","Transfer Queue"],
 e:"Many design numbers trace back to TQs (e.g. CIL4 carbon advance, lime system design)."},
{t:"acro",q:"'Doré'?",a:["The gold/silver bar poured in the goldroom, sent to the refinery","A type of cathode","A Knelson bowl","Barren solution"],
 e:"Electrowon sludge is dried and smelted with fluxes into doré bars. The refinery separates gold from silver and other metals."},
{t:"acro",q:"'Pregnant' vs 'barren' solution?",a:["Pregnant carries dissolved gold; barren has had the gold removed","Pregnant is hot; barren is cold","Pregnant is acid; barren is caustic","Pregnant is from CIL4; barren from CIL2"],
 e:"Same idea for carbon: loaded carbon holds gold, barren carbon is stripped. Lean eluate is partly used eluate recycled for the next strip."},

// ───────────────────────── CRUSHING ─────────────────────────
{t:"crush",q:"What type of primary crusher is in the new crushing area?",
 a:["Gyratory crusher (1300 × 1900 TSUV)","Jaw crusher","Cone crusher","Impact crusher"],
 e:"A gyratory has a gyrating mantle inside a fixed concave bowl. It handles the huge throughput (design 3,135 t/h) and ROM top size near 1 m. Existing Primary Crushing 1 has a 54-75 Mk II gyratory."},
{t:"crush",q:"Which truck is the dump pocket designed around?",
 a:["CAT 793F (about 250 t payload)","CAT 777","Komatsu 930E","Road trains"],
 e:"The dump pocket is direct tip from two sides, sized around the 793F heaped tray volume (about 179 m³ live from one side)."},
{t:"crush",q:"Why is the crusher design rate (≈3,135 t/h) much higher than the mill rate (≈1,833 t/h for the new circuit)?",
 a:["Crushing availability is only ~65% vs ~93% for milling, so it must crush faster while it runs","The crusher also feeds the waste dump","Half the crushed ore is rejected","The mill runs on two shifts only"],
 e:"Classic surge design. The crusher stops for truck gaps, blockages and maintenance, so it runs faster when running, and the stockpile evens it out. Same logic as sizing a compressor with a receiver."},
{t:"crush",q:"What's the typical crushed product size to the mills?",
 a:["P80 around 130 mm","P80 around 13 mm","P80 around 1.3 mm","P80 around 500 mm"],
 e:"The new crusher gives P80 about 130 mm (145 mm in the high throughput case). The SAG mill is designed around that feed."},
{t:"crush",q:"What sits between the primary crusher and the conveyor to the stockpile?",
 a:["An apron feeder under the crusher discharge","A ball mill","A thickener","A cyclone"],
 e:"Apron feeders are heavy steel pan conveyors that take impact and control the draw rate. There's also a tramp magnet on the stockpile feed conveyor."},
{t:"crush",q:"How is ore reclaimed from the new coarse ore stockpile to the SAG mill?",
 a:["Apron reclaim feeders under the stockpile onto the SAG feed conveyor, plus one emergency feeder fed by loader","By front end loader only","By bucket wheel reclaimer","By slurry pump"],
 e:"Two reclaim apron feeders draw ore through tunnels under the pile. The emergency feeder lets a 992K/994K loader keep the mill fed if the live stockpile runs low."},
{t:"crush",q:"'Live capacity' of a stockpile is...",
 a:["The tonnage that can be drawn by the feeders without dozing (about 20,000 t for the new COS)","The total tonnage on the pad","The tonnage crushed per day","The tonnage above the conveyor"],
 e:"Only the cone of material above the draw points flows freely (drawdown angle about 60°). Dead stock outside that needs a dozer or loader. Live capacity at design is about 11 hours of new circuit feed."},
{t:"crush",q:"What's the job of the wet scrubber / dust collector at the crusher?",
 a:["Capture dust generated by tipping and crushing","Wash the ore before crushing","Cool the crusher oil","Recover fine gold"],
 e:"Tipping 250 t loads makes a lot of dust. The scrubber and ventilation fans keep dust exposure and emissions in check."},
{t:"crush",q:"What does 'Primary Crushing 1' vs 'Primary Crushing 2' refer to on the PFDs?",
 a:["PC1 is the existing Fimiston crusher (F10); PC2 is the new crusher (F12)","PC1 is day shift; PC2 is night shift","PC1 crushes ore; PC2 crushes pebbles","PC1 and PC2 are two chambers in one crusher"],
 e:"Both feed coarse ore stockpiles. PC1 feeds the Fimiston stockpile and SAG feed conveyor, PC2 feeds the new stockpile for the new SAG."},

// ───────────────────────── MILLING ─────────────────────────
{t:"mill",q:"The plant now has two SAG mills. How do they relate to the ball mill?",
 a:["Both the existing Fimiston SAG and the new SAG discharge to the new primary cyclone feed hopper, sharing the new ball mill and cyclones","Each SAG has its own ball mill","The old SAG feeds the new SAG","The old SAG is scrapped"],
 e:"The Fimiston SAG (F19) discharge is pumped by the Fimiston mill transfer pumps to the primary cyclone feed hopper. Total mill feed is about 3,146 t/h nominal (≈1,313 t/h old SAG + ≈1,833 t/h new SAG)."},
{t:"mill",q:"What happens to SAG discharge screen oversize (pebbles)?",
 a:["It goes to the pebble (recycle) crushers and is returned to SAG feed","It goes to the ball mill","It goes to tailings","It goes to gravity"],
 e:"Pebbles are the 'critical size' rocks (roughly 12 to 75 mm) too small to break other rocks but too big to be ground quickly. Crushing them to about 12 mm P80 frees up SAG capacity."},
{t:"mill",q:"What type of pebble crushers are used on the new circuit?",
 a:["Two cone crushers (XL7), duty/duty","One jaw crusher","Two gyratories","A HPGR"],
 e:"Two XL7 cone crushers, 375 kW each, CSS about 7 mm. Pebble load is about 17 to 28% of new feed depending on case."},
{t:"mill",q:"Why are tramp magnets and a metal detector important ahead of the pebble crushers?",
 a:["Worn grinding balls and steel in the pebbles can wreck a cone crusher running a 7 mm gap","To recover gold","To reduce power draw on the SAG","To keep pebbles dry"],
 e:"SAG pebbles include broken and worn balls. Steel in a cone crusher closed side causes huge force spikes. So pebbles pass magnets before the crushers, and there's a bypass route for pebbles when crushers are down."},
{t:"mill",q:"What drives the SAG pebble ports size and why does it matter?",
 a:["75 mm pebble ports in the discharge grate. As they wear bigger, pebble load increases","They set the ball size","They control water addition","They set the mill speed"],
 e:"The discharge grate acts like a screen. Worn, enlarged pebble ports let more pebbles out, which is why the pebble crusher design allows up to 610 t/h."},
{t:"mill",q:"Where do the cyclone underflow and overflow go?",
 a:["Underflow (coarse) → ball mill; overflow (fine) → trash screens → flotation","Underflow → flotation; overflow → ball mill","Both to the SAG mill","Underflow → tailings; overflow → CIL4"],
 e:"Hydrocyclones separate by size and density. Coarse, heavy particles spin to the wall and exit the bottom (spigot) back to the ball mill. Fines exit the top (vortex finder) to flotation."},
{t:"mill",q:"What's the primary cyclone arrangement?",
 a:["One 800CVX cluster with 17 cyclones installed: 15 on primary duty and 2 on gravity duty","Four clusters of 6","One big cyclone","Two clusters of 8"],
 e:"About 12 primary cyclones run nominally (up to 14), with a standby. The 2 gravity cyclones are set up with larger spigots to push about 1,000 t/h each toward gravity."},
{t:"mill",q:"If cyclone feed density goes up too high, what's the likely effect on overflow grind?",
 a:["Coarser overflow (P80 goes up), because classification gets less sharp","Finer overflow","No change","The cyclone stops completely"],
 e:"Denser feed means more hindered settling, so coarse particles get dragged to overflow. Design feed density is about 62% solids w/w. Operators control it with water addition at the cyclone feed hopper."},
{t:"mill",q:"What does 'roping' in a cyclone indicate?",
 a:["The underflow is overloaded and discharging as a solid rope instead of a spray, sending coarse material to overflow","The cyclone is under water","The overflow pipe has ruptured","Normal operation"],
 e:"A healthy underflow discharges as an umbrella spray. Roping means the spigot is too small for the solids load. Coarse material then short circuits to flotation, which hurts recovery."},
{t:"mill",q:"Why are there trash screens between the cyclone overflow and flotation?",
 a:["To remove wood, plastic, rubber and grit that would block cells, UFG mills and carbon screens","To remove gold","To thicken the slurry","To add air"],
 e:"There are 4 linear trash screens (3 operating, 1 standby) with 1.0 mm apertures. Trash removed is about 27 t/day. Trash is a big nuisance downstream: it blinds intertank screens and floats with carbon."},
{t:"mill",q:"The ball mill is an 'overflow' type. What does that mean?",
 a:["Slurry discharges by overflowing through the trunnion at the discharge end (no grate)","It overflows onto the floor by design","It has a pebble grate like the SAG","It is fed from the top"],
 e:"Overflow ball mills let slurry exit through the discharge trunnion like a weir. A trommel on the discharge catches scats. The ball mill is 8.53 m × 13.26 m EGL with a 20 MW motor."},
{t:"mill",q:"What's the SAG mill discharge density target?",
 a:["About 75% solids w/w","About 35% solids","About 10% solids","About 95% solids"],
 e:"Mills run thick (≈75% w/w) so the slurry coats the charge and transfers impact energy. Too dilute and balls hit liners; too thick and the mill can overload."},
{t:"mill",q:"SAG mill power rising and bearing pressure climbing, with throughput unchanged. Most likely?",
 a:["The mill load is building (overloading), often from harder or coarser feed","The mill is empty","The trommel is torn","The ball mill tripped"],
 e:"Load and power track together up to a point. An overloading SAG needs feed reduced, speed or water adjusted. Past the peak, power can actually drop as the charge stops tumbling efficiently, which is why operators watch bearing pressure too."},
{t:"mill",q:"Why use Poly-Met liners in the ball mill and steel liners in the SAG?",
 a:["Steel handles SAG impact; rubber/steel composite Poly-Met gives lighter, longer life liners for the ball mill's lower impact duty","Poly-Met is cheaper to buy for SAG mills","Steel is used for UFG mills","Liners are chosen by colour"],
 e:"SAG mills see big rock and ball impact so they need hard steel. Ball mills see finer grinding and more abrasion, where composite liners work well and weigh less."},
{t:"mill",q:"What happens to the gravity scalping screen oversize?",
 a:["It goes to ball mill feed","It goes to the Knelsons","It goes to the ILR","It goes to tailings"],
 e:"The scalping screens (3.2 then 2.0 mm slots) protect the Knelsons from oversize. Oversize (about 10%) goes back to the ball mill, undersize goes to the Knelson concentrators."},

// ───────────────────────── GRAVITY ─────────────────────────
{t:"grav",q:"What type of gravity concentrator is used and how many?",
 a:["Two Knelson KC-QS70 centrifugal concentrators","Four spirals","Six jigs","One shaking table"],
 e:"Each Knelson takes up to ~1,000 t/h of slurry. A fluidised bowl spins at high G. Heavy gold is trapped in the riffles while lighter material washes through."},
{t:"grav",q:"What is 'fluidising water' on a Knelson and why is it critical?",
 a:["Water injected through the bowl rings to keep the concentrate bed loose so heavy particles can penetrate and light ones wash out","Wash water for the floor","Cooling water for the motor","Water for the tails pump gland"],
 e:"About 120 m³/h per unit. Too little and the bed compacts and loses gold. Too much and gold is washed out. Blocked fluidising holes are a common maintenance item."},
{t:"grav",q:"How does a Knelson produce concentrate?",
 a:["In batches: it runs a cycle (about 30 min), then stops feeding and flushes the concentrate out (about 150 kg per cycle)","Continuously out of the bottom","By flotation","By magnetic separation"],
 e:"48 cycles a day produce about 14 t/day of concentrate. That concentrate is dewatered and sent to the ILR."},
{t:"grav",q:"Where do Knelson tails go?",
 a:["Back to the primary cyclone feed hopper","To the CIL4 feed","To the TSF","To the ILR"],
 e:"Gravity is run on a circulating stream, so tails simply rejoin the grinding circuit. That's why it can catch gold repeatedly as it circulates."},
{t:"grav",q:"What does the ILR do with the Knelson concentrate?",
 a:["Leaches it in a batch with strong cyanide and oxygen, recovering about 98% of the gold into a pregnant solution","Smelts it directly","Floats it","Grinds it"],
 e:"The Acacia CS10000 runs 1 to 2 batches a day, about 12 h per cycle, making about 14.5 m³ of very rich pregnant solution (over 1,000 ppm Au)."},
{t:"grav",q:"Where does the ILR pregnant solution go?",
 a:["Gravity electrowinning cells in the goldroom (F66)","CIL4","The tailings dam","The flotation cells"],
 e:"Gravity EW uses clean in place cells, runs about 10 h per batch, and drives barren solution under 5 ppm Au."},
{t:"grav",q:"Why keep gravity gold separate rather than letting CIL collect it?",
 a:["Coarse gold leaches slowly and can escape to tails; gravity plus ILR gets it out fast and securely","Because CIL can't handle any gold","Because gravity gold is radioactive","Because of silver content only"],
 e:"It also reduces gold inventory in the circuit and gives fast gold for production. Gravity recovery is about 14% of feed gold nominal."},

// ───────────────────────── FLOTATION ─────────────────────────
{t:"flot",q:"How are the rougher and scavenger cells arranged?",
 a:["3 rougher tank cells in series followed by 4 scavenger tank cells, all forced air","4 roughers then 3 scavengers, self aspirated","1 rougher and 1 scavenger Jameson","7 cells in parallel"],
 e:"F16-CF-411 to 413 are Rougher 1, 2 and 3. F16-CF-414 to 417 are Scavenger 1 to 4. Slurry flows by gravity cell to cell. Blowers supply low pressure air."},
{t:"flot",q:"What is the significance of the scavenger cells?",
 a:["They are the last chance to catch slower floating sulphides before they go to tails, where locked gold is largely lost","They make the highest grade concentrate","They remove trash","They thicken the tails"],
 e:"Whatever the scavengers miss goes to CIL4, where only about a third of the remaining gold is recovered. So scavenger air, froth depth and reagent dosing directly decide how much refractory gold escapes."},
{t:"flot",q:"Where does Rougher 1 concentrate go?",
 a:["It can report straight to the final concentrate hopper because it's already high grade (about 15% S)","It always goes to the scavengers","To tailings","Back to the SAG"],
 e:"The PFD shows a Rougher 1 collection box with a final concentrate sampler routed to the final concentrate hopper. Fast floating, high grade material doesn't need cleaning."},
{t:"flot",q:"Where do Rougher 2 & 3 concentrate and Scavenger concentrate go?",
 a:["To the cleaner circuit (Jameson cleaner cell)","Direct to final concentrate","To the flotation tails thickener","To the ball mill"],
 e:"These concentrates are lower grade (about 7% S and 5% S) with more gangue, so they're upgraded in the cleaner."},
{t:"flot",q:"Where do cleaner tails go?",
 a:["To the cleaner-scavenger Jameson cell","To final concentrate","To CIL2","To the SAG mill"],
 e:"The cleaner rejects gangue, but its tails still carry some sulphide. The cleaner-scavenger gives it another pass. Cleaner-scavenger concentrate returns to the cleaner feed."},
{t:"flot",q:"Where do cleaner-scavenger tails go?",
 a:["To the flotation tailings thickener, joining the scavenger tails for CIL4","To the final concentrate","Back to the rougher feed","To the ILR"],
 e:"Flotation tails thickener feed = scavenger tails + cleaner-scavenger tails."},
{t:"flot",q:"What type of cells are the cleaner and cleaner-scavenger?",
 a:["Glencore Jameson cells (B6500/24), naturally aspirated via downcomers","FLS forced air tank cells","Column cells with spargers","Mechanical self aspirated cells"],
 e:"In a Jameson cell, slurry is pumped as a plunging jet down downcomers, which sucks in air and makes very fine bubbles. High intensity, small footprint, great for cleaning."},
{t:"flot",q:"The Jameson cells have an 'external recycle'. Why?",
 a:["Part of the tails is recirculated to the feed hopper to keep downcomer flow (and jet pressure) constant regardless of new feed rate","To send tails to the SAG","To add frother","To heat the slurry"],
 e:"A Jameson needs a steady volumetric flow through its downcomers. About half of the tails are recycled so new feed variations don't upset the jet. It's like a pump minimum flow bypass."},
{t:"flot",q:"Reagents in flotation. Match: collector / activator / frother.",
 a:["PAX / copper sulphate / Luprofroth 168","Lime / cyanide / PAX","Frother / lime / caustic","Copper sulphate / PAX / lime"],
 e:"Collector makes sulphides hydrophobic, activator conditions the pyrite surface, frother stabilises bubbles and froth."},
{t:"flot",q:"Froth in the rougher looks flat, watery and collapsing. Likely cause?",
 a:["Too little frother or collector, or too much water; weak froth drops recovery","Too much air only","High cyclone pressure","The SAG is overloading"],
 e:"A healthy froth is loaded with mineral and stable. Watery froth means poor mineral loading. Operators trim frother, collector, air rate and froth depth (level) in response."},
{t:"flot",q:"Raising the air rate on the scavengers generally...",
 a:["Increases mass pull and recovery but lowers concentrate grade","Lowers recovery","Has no effect","Only changes slurry temperature"],
 e:"More air lifts more material, including gangue. That's why scavenger concentrate goes to the cleaner rather than straight to final concentrate."},
{t:"flot",q:"What are the nominal rougher and scavenger residence times?",
 a:["About 15 min rougher and 21 min scavenger (≈37 min combined)","About 2 min each","About 3 hours each","About 1 min rougher, 60 min scavenger"],
 e:"Residence time = cell volume / slurry flow (adjusted for air hold up). Rougher total volume is 1,890 m³ (3 cells), scavenger 2,520 m³ (4 cells), so 630 m³ each."},
{t:"flot",q:"Nominal flotation gold recovery (of feed gold)?",
 a:["About 72% of gold (and about 85% of sulphur) to concentrate","About 20%","About 99%","About 40%"],
 e:"Flotation Au recovery is about 71.8% nominal (max 75%). The remaining gold goes to CIL4 with the tails."},
{t:"flot",q:"Where does final flotation concentrate go?",
 a:["Final concentrate hopper, then pumped to the concentrate thickener (existing 30-TH-61)","Straight to CIL4","To the Knelsons","To the TSF"],
 e:"From the thickener, concentrate goes to filter feed tanks and on to the UFG mills."},
{t:"flot",q:"Why does flotation feed pass an onstream analyser and samplers?",
 a:["To measure head grade (Au/S proxies) so recovery and reagent dosing can be tracked in near real time","To measure pH only","To add air","To count bubbles"],
 e:"Feed, concentrate and tail assays let metallurgists calculate recovery around the circuit every shift."},

// ───────────────────────── CONCENTRATE & UFG ─────────────────────────
{t:"conc",q:"How many UFG mills treat concentrate in Stage 2?",
 a:["Three IsaMills: UFG 1 (M3000, existing) plus UFG 2 and 3 (M15,000, new)","One ball mill","Two vertimills","Five tower mills"],
 e:"UFG 2 and 3 each take about 30 t/h fresh feed nominal (46 t/h max). UFG 1 handles about 10 t/h when running."},
{t:"conc",q:"What is the UFG product size target?",
 a:["P80 ≈ 9 µm (range 9 to 12 µm)","P80 ≈ 180 µm","P80 ≈ 1 mm","P80 ≈ 75 µm"],
 e:"For scale, a human hair is about 70 µm. The whole ore is ground to 180 µm, but concentrate is ground 20 times finer to crack the pyrite."},
{t:"conc",q:"Roughly how much energy per tonne does UFG use vs the ball mill?",
 a:["About 116 kWh/t for UFG vs roughly 8 to 10 kWh/t for the ball mill","About the same","UFG uses less","About 1,000 kWh/t for UFG"],
 e:"Grinding energy rises steeply as size drops. It's only economic because concentrate is about 4% of the ore mass. Each new IsaMill draws about 3.5 MW."},
{t:"conc",q:"How does an IsaMill differ from a ball mill?",
 a:["It's a horizontal stirred mill: discs on a shaft spin small ceramic/sand media at high speed; the tumbling shell doesn't rotate","It's just a smaller ball mill","It uses steel balls in a rotating drum","It crushes rock between rolls"],
 e:"Stirred mills transfer energy through attrition and shear, which is far more efficient at micron sizes than tumbling. Media is a few mm in size."},
{t:"conc",q:"Why are there static trash screens ahead of UFG 2 and 3?",
 a:["Any trash (wood fibre, plastic) would block the IsaMill's product separator and screens","To classify gold","To add water","To aerate"],
 e:"Inclined static wedge wire screens with 1.0 mm apertures. There was even a variation to add a trash screen on UFG Mill 2."},
{t:"conc",q:"What happens to concentrate in excess of UFG capacity?",
 a:["It goes through the existing vacuum belt filters to a concentrate stockpile","It's sent to CIL4","It's dumped at the TSF","It's recycled to the SAG"],
 e:"Filter cake target is under 10% moisture, and stockpiled concentrate needs to be under its Transportable Moisture Limit if it's to be moved in bulk."},
{t:"conc",q:"After UFG, where does the ground concentrate go before leaching?",
 a:["The concentrate pre-leach thickener (existing 30-TH-31, repurposed)","Straight to CIL4","The final tails tank","Back to flotation"],
 e:"Thickening to about 52 to 58% solids gives more residence time in the leach and recovers water. Underflow feeds CIL2."},
{t:"conc",q:"In Stage 2, what are CIL2 and CIL3 used for?",
 a:["CIL2 is repurposed for leach duty; CIL3 is repurposed for adsorption duty","Both are carbon regeneration","CIL2 is flotation, CIL3 is gravity","Both are decommissioned"],
 e:"It works like a leach-then-CIL train: gold dissolves in CIL2 (7 tanks), then carbon in CIL3 (6 tanks) adsorbs it."},
{t:"conc",q:"Why is the concentrate leach run at high pH (about 11.75 to 12.5) and with lead nitrate?",
 a:["High pH keeps cyanide as CN⁻ (not HCN gas); lead nitrate helps overcome sulphide passivation and speeds gold dissolution","To float the sulphides","To dissolve carbon","To reduce oxygen demand to zero"],
 e:"Fine sulphide concentrate is very reactive and consumes cyanide and oxygen. Lead nitrate is dosed at the leach feed box to counter that."},
{t:"conc",q:"The concentrate leach uses very high cyanide concentrations (thousands of ppm) compared to CIL4. Why?",
 a:["Concentrate is rich in gold and cyanide consuming sulphides, so it needs aggressive leaching to hit ~90% extraction","To destroy the carbon","Because CIL4 has no cyanide","To make the slurry lighter"],
 e:"Design leach extraction for concentrate was lifted to 90%. CIL3 tails, still carrying cyanide, flow on to CIL4 so that cyanide keeps working."},
{t:"conc",q:"Where do CIL3 tails go?",
 a:["To the CIL4 feed distribution box","To the TSF directly","Back to UFG","To the Knelsons"],
 e:"Sending CIL3 tails to CIL4 gives a second chance to recover any dissolved gold and reuses residual cyanide."},
{t:"conc",q:"Typical loaded carbon grade in CIL3 vs CIL4?",
 a:["About 4,500 g/t in CIL3 vs roughly 330 to 580 g/t in CIL4","About the same","CIL4 is higher","Both about 50 g/t"],
 e:"Concentrate solution is much richer, so carbon loads far higher. CIL3 carbon is stripped in the existing elution circuits (F65)."},
{t:"conc",q:"How is oxygen added in the CIL2 leach?",
 a:["Side lances on the tanks plus oxygen circulating/injection pumps on the first tanks","Blowers under the tanks","Hydrogen peroxide only","It isn't"],
 e:"Sulphide concentrate consumes oxygen fast. Oxygen injection pumps shear oxygen into the slurry for high DO."},

// ───────────────────────── CIL4 ─────────────────────────
{t:"cil4",q:"What feeds the flotation tailings thickener?",
 a:["Scavenger tails and cleaner-scavenger tails","Cyclone overflow","Concentrate","CIL3 tails"],
 e:"About 3,000 t/h of solids at about 33% solids. The thickener lifts it to about 56% solids underflow."},
{t:"cil4",q:"Why thicken flotation tails before CIL4?",
 a:["Removing water shrinks the slurry volume so the same tanks give more leach residence time, and recovers water","To add oxygen","To float residual sulphides","To grind finer"],
 e:"Going from ~33% to ~56% solids roughly halves the slurry volume. Thickener overflow is recycled as process water."},
{t:"cil4",q:"What is the CIL4 tank layout on the PFD?",
 a:["8 tanks in series: 2 leach tanks (TK-411/412) then 6 adsorption tanks (TK-413 to 418), with space for a future tank","20 small tanks","2 tanks only","One pachuca"],
 e:"Each tank is about 5,600 m³ live. Total leach plus adsorption residence is about 12.8 h nominal, a bit under the 14 h ideal, which is why a future extra tank was allowed for."},
{t:"cil4",q:"How does carbon move in CIL4?",
 a:["Counter current: carbon is pumped upstream (toward the feed) while slurry flows downstream","Same direction as slurry","It stays in one tank","It's added at the last tank only and removed there"],
 e:"Barren (regenerated) carbon enters at the last tank where solution gold is lowest. It's advanced tank to tank upstream, loading more each step, and pulled out loaded from the first adsorption tank. Like a counterflow heat exchanger."},
{t:"cil4",q:"What do intertank screens do in CIL4?",
 a:["Hold carbon in each tank while letting slurry pass to the next tank","Remove trash","Classify ore","Add cyanide"],
 e:"Kemix mechanically swept pumped screens with 1.0 mm wedge wire. Carbon (≈1 to 3 mm) stays, slurry (P80 ~180 µm) passes. If they blind or overflow, carbon can migrate the wrong way."},
{t:"cil4",q:"What's the 'Carbon Scout'?",
 a:["An automatic sampler that measures carbon concentration in each CIL4 tank","A person who inspects carbon","A carbon regeneration kiln","A drone"],
 e:"Gekko Carbon Scout samples all CIL4 tanks. Carbon concentration target is about 12.5 g/L. It tells operators when to advance carbon and whether carbon is distributed evenly."},
{t:"cil4",q:"CIL4 leach pH is about 8.8 to 9.3, much lower than CIL2. Why is that typical at KCGM?",
 a:["The hypersaline process water buffers pH; pushing it higher costs a lot of lime due to magnesium precipitation","Because cyanide works better at pH 7","Because there's no lime system","To dissolve the carbon"],
 e:"Process water SG is about 1.07 because it's saline bore water. Magnesium in the water consumes lime, so the bulk tails leach runs lower pH to control reagent cost, with safety controls for HCN."},
{t:"cil4",q:"CIL4 leach gold extraction is quite low (about 34 to 38%). Why is it still worth running?",
 a:["It treats ~96% of the mass; even a modest % of the gold in that huge tonnage is a lot of ounces","It isn't worth it","It recovers copper","It's needed for water balance"],
 e:"Most of the tails gold is locked in unfloated sulphides, so leach extraction is limited. But at ~3,000 t/h, a few tenths of a g/t recovered is significant gold."},
{t:"cil4",q:"Where does loaded carbon from CIL4 go?",
 a:["Pumped from the first adsorption tank to the CIL4 loaded carbon screen, then the transfer vessel, then the CIL4 elution column (F22)","To the SAG mill","To the TSF","To CIL3"],
 e:"The loaded carbon screen separates carbon from slurry. Slurry returns to the CIL4 tanks."},
{t:"cil4",q:"Where do CIL4 tails go?",
 a:["Final tails tank, then tailings disposal pumps to the TSF","Back to flotation","To UFG","To the goldroom"],
 e:"Acid wash waste and fine carbon waste also go to the final tails tank. Tails are sampled first (primary sampler) for metallurgical accounting."},
{t:"cil4",q:"What is the CIL4 static screen for?",
 a:["Screening event pond / silt trap slurry (spillage) before it's returned so trash doesn't enter CIL4","Loaded carbon recovery","Final tails sizing","Gravity scalping"],
 e:"A sieve bend with a 1 mm wedge wire. Spillage return is a common trash source."},
{t:"cil4",q:"What is a 'carbon safety screen'?",
 a:["A screen on leach tails to catch any carbon escaping the last tank before it's lost to the TSF","A guard over the carbon kiln","A screen protecting operators","A screen in the goldroom"],
 e:"Carbon lost to tails takes its loaded gold with it. CIL4's carbon safety screens are shown as future equipment in the PDC."},

// ───────────────────────── ELUTION ─────────────────────────
{t:"elu",q:"What's the sequence of a typical AARL strip?",
 a:["Acid wash → water rinse → caustic cyanide pre-soak → hot water elution → cool down → carbon out to regeneration","Elution → acid wash → kiln → CIL","Kiln → acid wash → elution","Pre-soak → kiln → acid wash"],
 e:"Acid removes carbonate scale that blocks carbon pores. The pre-soak loosens the gold. Hot water elution strips it into pregnant eluate."},
{t:"elu",q:"Why is the elution column kept under pressure?",
 a:["To stop the hot solution flashing (boiling) inside the column","To push carbon upward","To reduce cyanide","To aerate carbon"],
 e:"Elution runs well above 100 °C, so pressure keeps it liquid. Same principle as a pressurised cooling system."},
{t:"elu",q:"What acid is used for acid washing carbon?",
 a:["Hydrochloric acid (HCl, about 3% w/v)","Sulphuric acid","Nitric acid","Citric acid"],
 e:"Dilute HCl dissolves calcium and magnesium carbonate scale. Acid waste goes to the final tails tank."},
{t:"elu",q:"The CIL4 elution uses a single column for two duties. Which?",
 a:["Acid wash and elution in the same column (duplex stainless SAF2205)","Leach and adsorption","Regeneration and quench","EW and smelting"],
 e:"The existing concentrate circuits have separate acid wash columns. CIL4 uses one combined column made of acid and chloride resistant duplex stainless steel."},
{t:"elu",q:"How is the CIL4 elution solution heated?",
 a:["LPG fired elution heater with heat exchangers","Electric kettle","Steam from the kiln","Solar"],
 e:"The TPE LPG heater package heats the eluate. Hence LPG shows up in the reagent/utilities list."},
{t:"elu",q:"What happens to barren (stripped) carbon?",
 a:["It's regenerated in a kiln (thermal reactivation), quenched, sized on a screen and returned to CIL","It's thrown away","It's sent to the SAG mill","It's used as fuel"],
 e:"Heating in a low oxygen atmosphere burns off organics that foul carbon pores. The sizing screen removes fines, which would otherwise pass through intertank screens and carry gold to tails."},
{t:"elu",q:"Why does the carbon regeneration kiln off gas need treatment?",
 a:["Mercury and organics driven off the carbon must be captured before release","To recover gold vapour","To cool the building","It's only for noise"],
 e:"Goldfields ores carry mercury, which loads on carbon and comes off in the kiln. A mercury abatement system and a regenerative thermal oxidiser treat the off gas."},
{t:"elu",q:"What happens in the goldroom?",
 a:["Gold is electrowon onto cathodes, the sludge is dried, fluxed and smelted into doré bars","Ore is weighed","Carbon is regenerated","Cyanide is mixed"],
 e:"F66 covers CIL4A/4B electrowinning and gravity electrowinning. High security area."},
{t:"elu",q:"What is 'lean eluate'?",
 a:["Partly depleted eluate saved from a strip and reused for the pre-soak/first stage of the next strip","Fresh water","Acid waste","Solution from the TSF"],
 e:"In split AARL, reusing lean eluate saves reagents and water. The first bed volumes of fresh water become the next strip's lean eluate."},

// ───────────────────────── UTILITIES ─────────────────────────
{t:"util",q:"Process water at KCGM has an SG of about 1.07. Why?",
 a:["It's hypersaline bore water (very high dissolved salts)","It contains slurry","It's heated","It's mixed with oil"],
 e:"Fresh water is scarce in the Goldfields, so the plant runs on saline bore water from borefields like Kaltails. That's why corrosion resistant materials and specific reagent behaviour matter."},
{t:"util",q:"What is 'scheme water' used for?",
 a:["Fresh (potable quality) water for gland seals, elution, reagent make up, safety showers and other duties that can't tolerate salt","Tailings dilution","Mill water","Dust suppression on haul roads only"],
 e:"Scheme water comes from the Goldfields pipeline and is expensive, so it's reserved for jobs that need clean water. Its SG is 1.00."},
{t:"util",q:"What is 'cyanide water'?",
 a:["Decant water returned from the TSF, still carrying some cyanide, reused in the plant","Fresh cyanide solution","Water used for the ILR only","Rain water"],
 e:"Reusing it saves water and cyanide. It's treated with hydrogen peroxide (inline mixers on the decant lines) to a residual WAD cyanide target."},
{t:"util",q:"What is 'gland water'?",
 a:["Clean water injected into slurry pump shaft seals to keep grit out and cool the packing","Water from the gland of a thickener","Tailings water","Wash water for the floors"],
 e:"A mechanical engineer's favourite. Loss of gland water means packing runs dry, overheats and slurry gets into the seal. The new UFG mills also use scheme water for gland seals."},
{t:"util",q:"What's the difference between 'HP process water' and 'mill water'?",
 a:["HP process water is pumped at high pressure for sprays and hose points; mill (circuit) water is lower pressure dilution water for mills and cyclone hoppers","They're the same","HP water is fresh, mill water is saline","HP water is hot"],
 e:"The PFDs show both distributions. Screen sprays, launder sprays and trash screens use HP process water."},
{t:"util",q:"What supplies air to the rougher and scavenger cells?",
 a:["Low pressure flotation blowers","Plant air compressors","The PSA plant","Nothing; they're self aspirating"],
 e:"FLS forced air tank cells take blower air. Jameson cells don't need blowers because the plunging jet entrains air."},
{t:"util",q:"Why is instrument air kept separate from plant air?",
 a:["Instruments and valve actuators need clean, dry, oil free air at stable pressure","Instrument air is oxygen","Plant air is higher pressure only","It isn't separate"],
 e:"Wet or dirty air fouls positioners and solenoids. Instrument air is dried and filtered with a receiver for backup."},
{t:"util",q:"What's lime used for, and how is it delivered?",
 a:["pH control in leach (to prevent HCN gas); quicklime is slaked to milk of lime and pumped round a ringmain","Flotation collector","Carbon regeneration","Gold smelting flux only"],
 e:"The Stage 2 lime system includes a slaking package. Dosing points are leach feed boxes."},
{t:"util",q:"Why is flocculant added to thickeners?",
 a:["It binds fine particles into larger flocs that settle faster, giving a clear overflow and dense underflow","It kills bacteria","It makes froth","It dissolves gold"],
 e:"Flocculant is a long chain polymer, mixed dilute and dosed at the thickener feed well. Overdose makes underflow sticky and hard to pump."},
{t:"util",q:"What is hydrogen peroxide used for?",
 a:["Destroying (oxidising) cyanide in decant/cyanide water","Flotation frother","Pickling cathodes","Cooling the kiln"],
 e:"Dosing is controlled from an online WAD cyanide analyser."},
{t:"util",q:"What is caustic (NaOH) mainly used for?",
 a:["Elution pre-soak solution and pH control in elution/EW","Flotation collector","Tailings dust suppression","Mill liner lubrication"],
 e:"The pre-soak is a caustic cyanide solution. Caustic also keeps electrowinning solution alkaline."},
{t:"util",q:"Why is oxygen a key 'reagent' at KCGM?",
 a:["Gold cyanidation needs dissolved oxygen, and sulphide rich slurries consume it quickly","It's used to float carbon","It fuels the kiln","It's for the goldroom furnace only"],
 e:"Oxygen is supplied from a PSA plant with liquid oxygen backup, fed to leach tanks, ILR and CIL4."},

// ───────────────────────── NUMBERS ─────────────────────────
{t:"nums",q:"Nominal Stage 2 plant throughput?",
 a:["About 25.5 Mtpa (with a 28.35 Mtpa high throughput case at P80 220 µm)","About 5 Mtpa","About 100 Mtpa","About 12 Mtpa"],
 e:"That's about 3,146 t/h through the mills at 93.4% availability. For comparison the old Fimiston circuit alone was about 10.5 Mtpa."},
{t:"nums",q:"Nominal head grade the design is based on?",
 a:["About 1.6 g/t Au and about 1% S","About 16 g/t Au","About 0.1 g/t Au","About 5% S and 8 g/t Au"],
 e:"Nominal 1.58 g/t Au and 1.02% S. The design grade case is 1.81 g/t Au and 1.49% S."},
{t:"nums",q:"Nominal overall gold recovery?",
 a:["About 84%","About 50%","About 99%","About 65%"],
 e:"Built from gravity (~14%), flotation concentrate leach (high) and tails leach (low). Stage 2 aims for a 1 to 2% uplift."},
{t:"nums",q:"Approximate annual gold production in the nominal Stage 2 design case?",
 a:["About 1.2 million ounces","About 120,000 ounces","About 12 million ounces","About 500,000 ounces"],
 e:"The PDC calculates roughly 1.19 Moz/a for the 25.5 Mtpa nominal case."},
{t:"nums",q:"How much flotation concentrate is produced per year (nominal)?",
 a:["About 876,000 t/a (roughly 100 t/h)","About 8.7 Mt/a","About 8,700 t/a","About 25 Mt/a"],
 e:"That's the feed that UFG 1, 2 and 3 plus the filters must handle."},
{t:"nums",q:"Concentrator availability vs crushing availability used in design?",
 a:["93.4% concentrator vs 65% crushing","100% vs 100%","65% concentrator vs 93.4% crushing","50% vs 50%"],
 e:"That difference is why the stockpile exists and why the crusher is sized for a much higher instantaneous rate."},
{t:"nums",q:"The new SAG mill motor is rated...",
 a:["20 MW","2 MW","200 kW","60 MW"],
 e:"Same as the ball mill (20 MW). The old Fimiston SAG was 12 MW. Each new UFG mill is 3.8 MW installed."},
{t:"nums",q:"Gravity cyclone underflow aims to send how much to each Knelson?",
 a:["About 900 to 1,000 t/h","About 10 t/h","About 5,000 t/h","About 100 t/h"],
 e:"Vendor recommended about 90% of the 1,000 t/h max, so about 900 t/h per unit, 1,800 t/h total to gravity."},
{t:"nums",q:"CIL4 carbon concentration target per tank?",
 a:["About 12.5 g/L","About 125 g/L","About 1.25 g/L","About 50 g/L"],
 e:"The carbon scout measures it. CIL3 runs higher (about 20 g/L) because its solution is richer."},
{t:"nums",q:"Tailings disposal pumps arrangement?",
 a:["Duty / duty / duty / standby","Single pump","Duty / standby","Gravity flow, no pumps"],
 e:"Three running with one standby gives redundancy on a critical line. If tails can't be pumped, the whole plant stops."},

// ───────────────────────── HANDOVER SCENARIOS ─────────────────────────
{t:"hand",q:"Handover: 'Pebble crushers both down, pebbles on bypass.' What should you expect on the SAG?",
 a:["Pebbles recirculate uncrushed so SAG load builds and throughput usually has to be cut","Throughput will go up","Flotation recovery improves immediately","Nothing changes"],
 e:"Critical size material builds up in the SAG. Operators typically back off feed, watch power and bearing pressure, and may adjust speed."},
{t:"hand",q:"Handover: 'Cyclone overflow P80 running coarse, around 230 µm.' Downstream concern?",
 a:["Poorer liberation, so flotation recovery drops and coarse sulphides can sand up in the cells","Better flotation","Less cyanide needed","UFG mills will stop"],
 e:"Grind is a trade off with throughput. Coarser grind = more tonnes but more gold locked in unliberated particles going to tails."},
{t:"hand",q:"Handover: 'Scavenger tails sulphur is creeping up on the OSA.' What does it mean?",
 a:["More sulphide (and locked gold) is escaping flotation to CIL4, so recovery is dropping","Concentrate grade is improving","The thickener is overloaded","CIL4 carbon is too high"],
 e:"Check air rates, froth levels, reagent dosing (PAX, CuSO₄, frother), feed grind and feed rate. This is the scavenger significance in action."},
{t:"hand",q:"Handover: 'Trash screen 2 is blinding, running 3 wide with no standby.' Why does it matter?",
 a:["With no standby, any further loss sends trash or overflow to flotation and downstream screens/UFG","It doesn't matter","It increases gravity recovery","It lowers cyanide use"],
 e:"4 screens installed, 3 needed. Blinding means reduced open area, overflow and possible bypass of trash. Wash down or change panels quickly."},
{t:"hand",q:"Handover: 'Flotation tails thickener underflow density dropped to 48%.' Effect on CIL4?",
 a:["More water goes to CIL4, cutting leach residence time and diluting reagents","Longer residence time","No effect","Higher pH"],
 e:"Target is about 56%. Causes: flocculant issues, overloading or rake problems. Watch rake torque and bed level too."},
{t:"hand",q:"Handover: 'Thickener rake torque high and climbing.' Main risk?",
 a:["The rake can bog and trip; a bogged thickener is a major outage","Improved clarity","Lower flocculant use","The overflow will freeze"],
 e:"Operators respond by increasing underflow pumping, raising rakes, reducing feed or flocculant. A classic mechanical risk area."},
{t:"hand",q:"Handover: 'Carbon Scout shows Tank 6 low on carbon and Tank 7 high.' Likely issue?",
 a:["Carbon distribution problem: intertank screen or carbon advance pump not moving carbon as intended","Leach pH too high","Knelson blocked","SAG overload"],
 e:"Carbon moves counter current by recessed impeller pumps. Uneven inventory reduces adsorption efficiency and can lead to soluble gold loss."},
{t:"hand",q:"Handover: 'DO low in CIL2 leach tanks.' What might be the cause and consequence?",
 a:["Oxygen supply or injection pump issue; slower gold dissolution and more cyanide consumption","Too much carbon","Coarse grind","Low lime in flotation"],
 e:"Check the PSA plant, liquid oxygen, lances and injection pumps. Sulphide concentrate is a big oxygen consumer."},
{t:"hand",q:"Handover: 'High WAD on decant return.' What system should respond?",
 a:["Hydrogen peroxide cyanide destruct dosing on the decant water lines","Flotation frother dosing","Pebble crushers","Knelson fluidising water"],
 e:"An environmental and safety item. The online CNWAD analyser controls peroxide dosing."},
{t:"hand",q:"Handover: 'Knelson 1 fluidising water flow low alarm.' Action and consequence?",
 a:["Investigate blocked rings/supply; low fluidisation compacts the bed and loses gold recovery","Ignore it","Increase frother","Stop the SAG"],
 e:"Fluidising water is about 120 m³/h per unit. Low flow usually means blockages or supply issues."},
{t:"hand",q:"Handover: 'UFG 2 offline for media top up, excess con going to filters.' What does that tell you?",
 a:["Concentrate beyond UFG 1 and 3 capacity is being filtered and stockpiled rather than leached right now","Flotation has stopped","CIL4 is offline","Gravity is on hold"],
 e:"The filters and stockpile act as the relief path for concentrate above UFG capacity."},
{t:"hand",q:"Handover: 'Elution on strip 2 of 3 for CIL4, kiln running.' What does 'strip' mean?",
 a:["One complete elution batch of loaded carbon","A strip of conveyor belt","Stripping liners from a mill","A cleaner cell"],
 e:"The CIL4 column does acid wash and elution in one vessel. Each strip then sends carbon to the regeneration kiln."},
{t:"hand",q:"Handover: 'SAG discharge screen panels worn, pebbles reporting to cyclone hopper.' Risk?",
 a:["Oversize can overload the cyclone feed pump and send coarse material to the ball mill and cyclones","Better grind","More gravity gold","No risk"],
 e:"The discharge screen (12 × 55 mm slots) keeps pebbles out of the slurry side. Worn panels let oversize through."},
{t:"hand",q:"Handover: 'Jameson cleaner recycle valve stuck open.' Why care?",
 a:["It changes the downcomer flow/pressure balance, affecting bubble generation and cleaner performance","It adds more collector","It stops the SAG","It changes carbon loading"],
 e:"The Jameson depends on a steady jet flow through the downcomers. The external recycle keeps that constant."},
{t:"hand",q:"Handover: 'Concentrate thickener overflow is dirty.' Main loss?",
 a:["Fine sulphide concentrate (with gold) is reporting to the overflow water","Pebbles","Carbon","Lime"],
 e:"Check flocculant dosing and thickener loading. Dirty overflow also contaminates process water."},
{t:"hand",q:"Handover: 'Final tails sampler down.' Why do metallurgists care?",
 a:["Final tails assays are needed for metallurgical accounting and recovery calculation","It affects throughput","It controls cyanide dosing","It controls the SAG"],
 e:"Without tails samples, recovery for the shift can't be confirmed."},
{t:"hand",q:"Handover: 'Fimiston SAG transfer pump tripped.' Which circuit is affected immediately?",
 a:["The old Fimiston SAG (F19) can't send discharge to the new cyclone feed hopper, so it must stop or reduce feed","The ILR","The CIL4 kiln","The UFG mills"],
 e:"Since both SAGs share the new cyclone cluster and ball mill, the transfer line is critical to running the old SAG."}
];
